services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ktaxes
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
  golang:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang
    ports:
      - "${PORT}:${PORT}"
